name: Docker Image CI
on:
  push:
    tags:
      - '*'
    branches:
      - 'release/*'
jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKER_PROJECTNAME: ${{ secrets.DOCKERHUB_PROJECTNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set env and version
        id: get_tag
        run: |
          if [[ $GITHUB_REF =~ ^refs/heads/release/.* ]]; then
            echo ::set-output name=ENVIRONMENT::uat
            echo ::set-output name=VERSION::release-$(echo ${GITHUB_REF#refs/heads/release/} | cut -d'/' -f 2)
          else
            echo ::set-output name=ENVIRONMENT::prod
            echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          fi
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci --force
      - name: Build React
        run: |
          if [[ ${{ steps.get_tag.outputs.VERSION }} == uat ]]; then
            npm run build:prod
          else
            npm run build:prod
          fi
      - name: Docker Login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:  ${{ env.DOCKER_USER }}/${{ env.DOCKER_PROJECTNAME }}:${{ steps.get_tag.outputs.VERSION }}