name: Docker Image CI
on:
  push:
    tags:
      - '*'
jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_PROJECT_NAME: ${{ secrets.DOCKER_PROJECT_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get tag version
        id: get_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci --force
      - name: Build React
        run: npm run build
      - name: Docker Login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $DOCKER_USER/$DOCKER_PROJECT_NAME:${{ steps.get_tag.outputs.VERSION }}
